"""initial database schema

Revision ID: 6a11a9812fa2
Revises: 
Create Date: 2026-05-09 11:59:13.206035
"""

from alembic import op
import sqlalchemy as sa



revision = '6a11a9812fa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('precision', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('recall', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('f1', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('auc', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_model_versions_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_version'), ['version'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('transaction_ref', sa.String(length=50), nullable=False),
    sa.Column('merchant', sa.String(length=120), nullable=True),
    sa.Column('merchant_type', sa.String(length=80), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Blocked', name='transaction_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_merchant'), ['merchant'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_type'), ['merchant_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_ref'), ['transaction_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_time'), ['transaction_time'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('alert_ref', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
    sa.Column('risk_level', sa.Enum('Low', 'Medium', 'High', name='alert_risk_level'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Resolved', name='alert_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_ref'), ['alert_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_alerts_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_type'), ['target_type'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('model_version_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
    sa.Column('fraud_probability', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('risk_level', sa.Enum('Low', 'Medium', 'High', name='risk_level'), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('prediction_explanations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('prediction_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('feature_name', sa.String(length=50), nullable=False),
    sa.Column('impact', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_explanations_feature_name'), ['feature_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_explanations_prediction_id'), ['prediction_id'], unique=False)

    op.create_table('review_cases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('case_ref', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('prediction_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('assigned_analyst_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='case_priority'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'In Review', 'Resolved', name='case_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cases_assigned_analyst_id'), ['assigned_analyst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_case_ref'), ['case_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_cases_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('case_decisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('case_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('analyst_id', sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
    sa.Column('decision', sa.Enum('fraud', 'safe', 'send_to_review', 'blocked', 'approved', name='case_decision'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['review_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_decisions_analyst_id'), ['analyst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_decisions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_decisions_decision'), ['decision'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_decisions_decision'))
        batch_op.drop_index(batch_op.f('ix_case_decisions_case_id'))
        batch_op.drop_index(batch_op.f('ix_case_decisions_analyst_id'))

    op.drop_table('case_decisions')
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cases_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_status'))
        batch_op.drop_index(batch_op.f('ix_review_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_review_cases_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_case_ref'))
        batch_op.drop_index(batch_op.f('ix_review_cases_assigned_analyst_id'))

    op.drop_table('review_cases')
    with op.batch_alter_table('prediction_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_explanations_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_explanations_feature_name'))

    op.drop_table('prediction_explanations')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_risk_level'))
        batch_op.drop_index(batch_op.f('ix_predictions_model_version_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_risk_level'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_ref'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_time'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_ref'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant'))

    op.drop_table('transactions')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_version'))

    op.drop_table('model_versions')
    # ### end Alembic commands ###
